<?php

use Drupal\Core\Routing\RouteMatchInterface;
function multilingual_google_web_translator_theme($existing, $type, $theme, $path)
{
return [
    'googletranslate' => [
        'variables' => ['google_translate' => []],
      ],
  ];
}

/**
 * Implements hook_help().
 */
function multilingual_google_web_translator_help($route_name, RouteMatchInterface $route_match) {
    if ($route_name == 'help.page.multilingual_google_web_translator') {
      return t('This module helps you implement Google translation for your webpage. It does not have any configuration settings. You just have to install it, after that you will see a Google Translation Block in your Blocks section. You can place this Block in any region within your webpage. It gives you a Select Box containing multiple languages, the default language is English, once you change the language from dropdown, your webpage content language will also get changed.');
    }
  }
